apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
      - name: envoy

# Configurar e aplicar os logs do Istio com um arquivo YAML, possibilitando o diagnóstico de conexões.